# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "04ff22b57a04144cfbbedcede3280b14"
name = "vehicule-compatible"
handle = "vehicule-compatible"
application_url = "https://ob-scratch-subscriptions-heat.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6713e4cf.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_content"

[auth]
redirect_urls = [
  "https://ob-scratch-subscriptions-heat.trycloudflare.com/auth/callback",
  "https://ob-scratch-subscriptions-heat.trycloudflare.com/auth/shopify/callback",
  "https://ob-scratch-subscriptions-heat.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[app_proxy]
url = "https://ob-scratch-subscriptions-heat.trycloudflare.com/app/api"
subpath = "vehicule-compatible"
prefix = "apps"

[pos]
embedded = false
